export const FakeData = [
  {
    id: "001",
    productName: "HelloPhone",
    productNameVn: "HelloPhoneVN",
    description: "English Description",
    descriptionVn: "Vietnam Description",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "002",
    productName: "HelloPhone 002",
    productNameVn: "HelloPhoneVN 002",
    description: "English Description 002",
    descriptionVn: "Vietnam Description 002",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "003",
    productName: "HelloPhone 003",
    productNameVn: "HelloPhoneVN 003",
    description: "English Description 003",
    descriptionVn: "Vietnam Description 003",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "004",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "005",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "006",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "007",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "008",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "009",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0010",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0011",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0012",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0013",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0014",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0015",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0016",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0017",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0018",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0019",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0020",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0021",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0022",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0023",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0024",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0025",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0026",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0027",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0028",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0029",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
  {
    id: "0030",
    productName: "HelloPhone 004",
    productNameVn: "HelloPhoneVN 004",
    description: "English Description 004",
    descriptionVn: "Vietnam Description 004",
    price: "20 $",
    priceVn: "200 &",
  },
];
